# Generated by Django 2.2.7 on 2019-12-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('anime_type', models.TextField(blank=True)),
                ('genres', models.TextField(blank=True)),
                ('premiered', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.User')),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
