# Generated by Django 2.2.7 on 2019-11-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
