# Generated by Django 2.2.7 on 2019-12-01 21:34

from django.db import migrations

import pickle
import pandas


def populate_database_with_anime_meta_data(apps, schema_editor):
    # Load Kaggle dataset and populate database with animes.
    path = "recommendations/migrations/meta.pickle"
    with open(path, "rb") as f:
        meta = pickle.load(f)

    Anime = apps.get_model('recommendations', 'Anime')

    for i,anime in meta.iterrows():
        obj, _ = Anime.objects.get_or_create(
            anime_id = anime.anime_id,
        )
        obj.title = anime.title
        obj.anime_type = anime.type
        obj.genres = anime.genre
        obj.premiered = anime.premiered
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_database_with_anime_meta_data),
    ]
