# Generated by Django 2.2.7 on 2019-11-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_anime_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='anime',
            name='id',
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='premiered',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.User')),
            ],
        ),
    ]
