# Generated by Django 2.2.7 on 2019-11-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_auto_20191130_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'anime')},
        ),
    ]
