# Generated by Django 2.2.7 on 2019-11-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_auto_20191130_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(default='', unique=True),
        ),
    ]
